---
services:
  app:
    depends_on:
      solr:
        condition: service_healthy
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - SOLR_URL=http://solr:8983/solr/blacklight-core
    env_file:
      - .env
  solr:
    depends_on:
      zookeeper:
        condition: service_healthy
    image: solr:9.7
    volumes:
      - solr-data:/var/solr
      - $PWD/solr/conf:/opt/solr/conf
    healthcheck:
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 5
      test: ["CMD-SHELL", "curl -s -f 'http://localhost:8983/solr/admin/collections?action=CLUSTERSTATUS'"]
    ports:
      - '8983:8983'
    command: solr-foreground
    environment:
      - SOLR_JAVA_MEM=-Xms1024m -Xmx1024m
      - SOLR_HEAP=1024m
      - ZK_HOST=zookeeper:2181
  zookeeper:
    image: zookeeper
    healthcheck:
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 5
      test: [ "CMD", "nc", "-z", "-w", "2", "localhost", "2181" ] # Check if ZooKeeper is listening on port 2181
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
volumes:
  solr-data:
