services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    working_dir: /workspaces/boxwalker
    env_file: []
    volumes:
      - .:/workspaces/boxwalker:cached
      - bundle-cache:/usr/local/bundle
      - node-modules:/workspaces/boxwalker/node_modules
    environment:
      SOLR_URL: http://solr:8983/solr/blacklight-collection
      BUNDLE_PATH: /usr/local/bundle

volumes:
  bundle-cache:
  node-modules:

