---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USERNAME", "myuser") %>
  password: <%= ENV.fetch("DB_PASSWORD", "secret") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "boxwalker") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "boxwalker") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "boxwalker") %>
